name: flutter_login
description: A login widget with login/signup functionalities to help speed up development
version: 1.0.14
author: NearHuscarl <near.huscarl@gmail.com>
homepage: https://github.com/NearHuscarl/flutter_login

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.5.0
  provider: ^4.0.2
  transformer_page_view: ^0.1.6
  flushbar: ^1.9.1
  carousel_widget: ^0.1.1
  form_bloc:
  flutter_form_bloc:
  flutter_bloc:
  http: ^0.12.0+4
  shared_preferences: ^0.4.2
  simple_gesture_detector: ^0.1.3
  json_annotation: ^3.0.1
  charts_flutter: ^0.9.0
  intl: ^0.16.1
  google_maps_flutter: ^0.5.24+1
  google_maps: ^3.4.1
  # flutter_test from sdk depends on quiver 2.0.5
  quiver: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  camera:
  path_provider:
  carousel_widget: ^0.1.1
  http: ^0.12.0+4
  simple_gesture_detector: ^0.1.3
  intl:	">=0.15.0 <0.17.0"
  flutter_calendar: ^0.0.1
  cupertino_icons: ^0.1.2
  table_calendar: ^2.0.1
  provider: ^4.0.4
  flutter_image_pick_crop:
  google_nav_bar: ^2.0.1
  google_fonts: 0.2.0
  responsive_screen: ^1.0.0
  flutter_cupertino_settings: ^0.3.0
  flutter_bloc: ^3.2.0
  dio: ^3.0.9
  equatable: ^1.1.1
  line_icons: ^0.2.0
  shimmer: ^1.1.0
  webview_flutter: ^0.3.19+9
  mime: ^0.9.6+3
  toast: ^0.1.5
  built_value: ^7.0.9
  built_collection: ^4.3.2
  url_launcher: ^5.4.2
  flutter_spinkit: 4.1.2
  flappy_search_bar: 1.4.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/ecorp.png
    - assets/images/ecorpchest.png
    - assets/images/hulk.png


  #  - assets/images/placeholder-logo.png
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
